"""
MedClaim — LangGraph Node Functions

Each function is a graph node that:
    1. Receives the full ClaimState
    2. Performs its processing (LLM call, RAG lookup, etc.)
    3. Returns a PARTIAL state dict with only the fields it updates

These are placeholder implementations for Subphase 2.1.
Full LLM-powered logic is implemented in Subphases 2.2–2.6.
"""

from __future__ import annotations

import logging
import time
from typing import Any

from backend.agents.state import ClaimState

logger = logging.getLogger("medclaim.agents.nodes")


# ── Eligibility Check Node ───────────────────────────────────

def eligibility_check(state: ClaimState) -> dict[str, Any]:
    """
    Verify patient insurance eligibility.

    Delegates to the EligibilityAgent which:
        1. Looks up payer in payer_directory.yaml
        2. Matches against eligibility_fixtures.yaml
        3. Checks coverage active, procedure covered, provider in-network
        4. Returns structured EligibilityResult
    """
    from backend.agents.eligibility import run_eligibility_check
    return run_eligibility_check(state)


# ── Code Audit Node ─────────────────────────────────────────

def code_audit(state: ClaimState) -> dict[str, Any]:
    """
    Audit ICD-10/CPT codes for accuracy.

    Delegates to the CodeAuditAgent which:
        1. Retrieves coding rules from Qdrant
        2. Retrieves payer policies from Qdrant
        3. Calls Groq/Gemini with structured system prompt
        4. Parses findings: upcoding, unbundling, missing modifiers
    """
    from backend.agents.code_audit import run_code_audit
    return run_code_audit(state)


# ── Denial Prediction Node ──────────────────────────────────

def denial_prediction(state: ClaimState) -> dict[str, Any]:
    """
    Predict denial risk using historical patterns.

    Delegates to the DenialPredictionAgent which:
        1. Retrieves similar claims from Qdrant (denial_patterns)
        2. Renders denial_prediction.j2 prompt with audit context
        3. Calls Groq/Gemini for risk assessment
        4. Returns risk_score (0-100) + risk_factors + recommended_action
    """
    from backend.agents.denial_prediction import run_denial_prediction
    return run_denial_prediction(state)


# ── Ready for Submission Node ────────────────────────────────

def ready_for_submission(state: ClaimState) -> dict[str, Any]:
    """Mark claim as ready for human-approved submission."""
    claim_id = state.get("claim_id", "unknown")
    logger.info("node.ready.complete | claim_id=%s", claim_id)

    return {
        "status": "READY_FOR_SUBMISSION",
        "current_agent": "ready_for_submission",
    }


# ── Appeal Drafting Node ─────────────────────────────────────

def appeal_drafting(state: ClaimState) -> dict[str, Any]:
    """
    Draft an appeal letter for a denied claim.

    Full implementation (Subphase 2.5) will:
        1. Retrieve payer policies (payer_policies collection)
        2. Retrieve clinical guidelines (clinical_guidelines collection)
        3. Call Gemini LLM (long context) with denial details
        4. Generate structured appeal letter with citations
        5. Return letter content + supporting document references

    Current: Placeholder returning a template appeal.
    """
    claim_id = state.get("claim_id", "unknown")
    denial_code = state.get("denial_reason_code", "UNKNOWN")
    start = time.time()
    logger.info("node.appeal_drafting.start | claim_id=%s denial_code=%s", claim_id, denial_code)

    letter_content = (
        f"APPEAL LETTER — Claim {claim_id}\n\n"
        f"Dear Claims Review Department,\n\n"
        f"We are writing to appeal the denial of claim {claim_id} "
        f"under denial reason code {denial_code}.\n\n"
        f"[Full appeal content will be generated by the Appeal Drafting Agent "
        f"in Subphase 2.5 using RAG-augmented LLM with clinical guidelines "
        f"and payer policy citations.]\n\n"
        f"Respectfully submitted."
    )

    latency = int((time.time() - start) * 1000)
    logger.info("node.appeal_drafting.complete | claim_id=%s latency_ms=%s", claim_id, latency)

    return {
        "appeal_letter_content": letter_content,
        "appeal_supporting_docs": [],
        "appeal_status": "DRAFT",
        "status": "APPEAL_DRAFT_READY",
        "current_agent": "appeal_drafting",
    }


# ── Human Review Node ───────────────────────────────────────

def human_review(state: ClaimState) -> dict[str, Any]:
    """
    Flag claim for human review and halt the pipeline.
    """
    claim_id = state.get("claim_id", "unknown")
    current_agent = state.get("current_agent", "unknown")
    confidence = state.get("audit_confidence", 0.0)
    risk_score = state.get("denial_risk_score", 0)

    # Determine reason for human review
    reasons = []

    if confidence < 0.80:
        reasons.append(
            f"Audit confidence {confidence:.2f} below 0.80 threshold"
        )

    if risk_score > 70:
        retry = state.get("retry_count", 0)
        reasons.append(
            f"Denial risk {risk_score}% after {retry} correction attempts"
        )

    if not reasons:
        reasons.append(f"Routed from {current_agent}")

    reason = "; ".join(reasons)

    logger.warning(
        "node.human_review.flagged | claim_id=%s reason=%s",
        claim_id,
        reason,
    )

    return {
        "human_review_flag": True,
        "human_review_reason": reason,
        "status": "HUMAN_REVIEW_REQUIRED",
        "current_agent": "human_review",
    }